language: java
jdk:
- openjdk7
- oraclejdk7
env:
  global:
  - secure: tlMPSRwLNtMX6sAPle28uItIUoWuWet2EDaWZprKPJsY5u/AmjOigDH6dJCwYFi7t1eWeueYeNgzQjKiVGe1kia00WoEaUwPo+P3C1hCjkKSfjLwMxqLR4VvEj/8FDRBoncwryNWWCCxSxEXL6OCGCUqCqy0eye2KaEV9RJCNoA=
  - secure: bXjOngFzBAcI5uiJyxAx2S9rptFK+Sp0Pa0LQKsPz/lFxCPhgJdhHGqEvpkzxAi41jmR/nTFB/F//a7lWUK3QfHQV9zU39T+nA17wjmpds2+1xYNTAea5ow3bBVelBL0MoIs+sNlwQhIFR7daVpTfnVEJNXCipEzJmLrKptWs7E=
  - secure: I1I4hrpOQ6ITx2LxmpQ4LgTsm6d2CTMu8NviUMDl9/7ozOojXxsPZI9pPieqB1BVGy9F+JgUs7SXi4v2Y4DHdqbh9DCCmtQviMJVUm3LDUEGjyTl650TtjnkfnU8J0Y0c31ThNUW2entDr4THNyNunXnX68mBaQjQqrZEuO9Jf0=
  - secure: iFXZeCjomL9KCUzQ+BFuWO9w+/uuunMadta1v/9ifZUGJAWfqyQ6Cc2S/COmOrcbYjE3ViPrj7fYbRBqgRl2yV0fuvy5Y+OMDIMwcMnVMDxLdId77aXTAd7LZ8z+wbpDRNlXyfiKP75CSHiMsFacJyMWYGkab715GzEF5UYcSZw=
before_install:
- sudo sed -i 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security
before_script:
- gem install travis-artifacts
script: mvn clean install
after_success:
- mvn jacoco:report coveralls:jacoco
deploy:
  provider: s3
  access_key_id: AKIAJJ3LVLR75WN6SVQA
  secret_access_key:
    secure: nOs9q5WEoxlGoS069Hke52JSXXOS8PotrdGwfr6ZFfFqBuhNPStnwjRDSjkGsOdzswfBH0NzuLmFYp8XrxmIzZ0RXKNJH8WT3T04le3EGgUkii8V17ZHAP8IHKFt8AG2O8QL89Gphceg0dAFXGYEMD45nSBNo15ZstkE4LwV86Y=
  bucket: s3fs-artifacts
  local-dir: target/surefire-reports
  upload-dir: surfire-reports
  acl: !ruby/string:HighLine::String |-
    cHJpdmF0ZQ==
  on:
    repo: Upplication/Amazon-S3-FileSystem-NIO2