name: Build and test workflow
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Commenting Windows out in order to preserve our free minutes.
        # We can re-enable it, if we get a sponsor.
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [ 8, 11.0.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # https://github.com/actions/cache/blob/master/examples.md#java---maven
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean install -Pjacoco-code-coverage
      - name: Publish code analysis to Sonarcloud
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11.0.3' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests

